server:
  port: 8084

spring:
  application:
    name: api-gateway

  config:
    import: "optional:configserver:"

  cloud:
    config:
      uri: http://localhost:8888

# Eureka Client Configuration added here
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true